### ISSUE TITLE
unable to generate webapp bundle

### ISSUE THREAD

**Issue by Shan-felix** [mattermost-community/mattermost-plugin-google-drive#13]
unable to generate webapp bundle: com.darklord.plugin-google-drive: unable to copy webapp bundle directory: com.darklord.plugin-google-drive: stat /mattermost/plugins/com.darklord.plugin-google-drive/webapp/dist: no such file or directory

**Comment by wiggin77** [comment]
@Shan-felix you need to make sure you have the right node/npm version.  `nvm install` in the project root will ensure this.  You'll also need Go 1.21 or better.  Then run `make dist` from the project directory.  I just tried this myself and it works.

**Comment by BenCookie95** [comment]
Closing issue as there is no reply
