### ISSUE TITLE
Starting and stopping the Drive activity notifications even if they are already started or stopped should show correct error.

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost-community/mattermost-plugin-google-drive#3]
This issue was found during the testing of this plugin.

**For start activity slash command:**
If the user runs the slash command "/drive notifications start" even if the notifications were already started (enabled), the user receives the message that the notifications have been started, instead, it should be that they are already enabled. This is a suggestion if we can work on it.

**For stop activity slash command:**
If the user runs the slash command "/drive notifications stop" even if the notifications were already stopped (disabled), the user should receive a message that they are already stopped, or there should be a consistency with the case above. But the user receives a message of something went wrong and contact your org admin.

**Comment by darkLord19** [comment]
@AayushChaudhary0001 this is fixed on master.

**Comment by AayushChaudhary0001** [comment]
This issue has been re-tested and fixed on the master branch, so we are closing this issue.
