### ISSUE TITLE
User not able to connect the account to the app created on Google cloud

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost-community/mattermost-plugin-google-drive#36]
On testing the master branch, it was found that I am not able to connect the account to the app created in Google cloud console. I have provided all the necessary permissions and this issue is reproducible on master branch. 

Steps to reproduce:-
1. Upload the plugin and complete the setup.
2. Run the connect slash command and click on the link provided.

The user should have been able to connect to the account, but instead receives an error on a new window stating "You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure."

I am also attaching the screenshot for the same:-
![image](https://github.com/user-attachments/assets/027eec8f-2e6d-4977-babe-428aad5bf0cc)

![image](https://github.com/user-attachments/assets/7bd16e7c-87c4-41c7-9829-d650c4363ee8)

Nothing much visible in server logs:-
`{"timestamp":"2024-11-21 23:10:30.992 +05:30","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:185","method":"POST","url":"/api/v4/channels/members/me/view","request_id":"tbp1b57motddzxn6pihddqiskc","user_id":"rf8y1tyhqpbydf89ggqfnm6xnh","status_code":"200"}
{"timestamp":"2024-11-21 23:10:31.955 +05:30","level":"debug","msg":"Websocket request","caller":"wsapi/websocket_handler.go:26","action":"user_typing"}
{"timestamp":"2024-11-21 23:10:31.984 +05:30","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:185","method":"POST","url":"/api/v4/commands/execute","request_id":"68pdy9dqgp8z8p3sdupkgx691r","user_id":"rf8y1tyhqpbydf89ggqfnm6xnh","status_code":"200"}
{"timestamp":"2024-11-21 23:10:32.097 +05:30","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:185","method":"POST","url":"/api/v4/channels/members/me/view","request_id":"pie5m7paujbr7eprj6n9c33z8e","user_id":"rf8y1tyhqpbydf89ggqfnm6xnh","status_code":"200"}
{"timestamp":"2024-11-21 23:10:32.208 +05:30","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:185","method":"DELETE","url":"/api/v4/users/me/channels/uti7sfz8ttdrugos5jouaam6qc/drafts","request_id":"65qunh65gtyoxpepc6u5y1a44e","user_id":"rf8y1tyhqpbydf89ggqfnm6xnh","status_code":"200"}
{"timestamp":"2024-11-21 23:10:35.877 +05:30","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:185","method":"POST","url":"/api/v4/channels/members/me/view","request_id":"wwj3w56fnpfhxr963x993k4roo","user_id":"rf8y1tyhqpbydf89ggqfnm6xnh","status_code":"200"}
{"timestamp":"2024-11-21 23:10:40.603 +05:30","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:185","method":"POST","url":"/api/v4/users/status/ids","request_id":"uopjmiwt4tdjtc56g9w6x8qs3o","user_id":"rf8y1tyhqpbydf89ggqfnm6xnh","status_code":"200"}
`

I am using the redirect URL as:-

<mattermost_URL>/plugins/com.mattermost-community.plugin-google-drive/oauth/complete

**Comment by BenCookie95** [comment]
Fixed here https://github.com/mattermost-community/mattermost-plugin-google-drive/commit/1e83bd6f1c8904d6585dc4d89876131628e5b76a
