### ISSUE TITLE
Fix the plugin crashing on running notification or create command without arguments.

### ISSUE THREAD

**Issue by arush-vashishtha** [mattermost-community/mattermost-plugin-google-drive#41]
**Summary:**
When the user enters the command "/google-drive notificaiton" or "/google-drive create" without the arguments the plugin crashes with an error message;
"/google-drive command crashed the com.mattermost-community.plugin-google-drive plugin. Please contact your system administrator"
and the log received in the server logs is:
```
{
  "caller": "web/context.go:124",
  "err_where": "ExecutePluginCommand",
  "error": "ExecutePluginCommand: /google-drive command crashed the com.mattermost-community.plugin-google-drive plugin. Please contact your system administrator, err= Plugin com.mattermost-community.plugin-google-drive crashed due to /google-drive command",
  "http_code": 500,
  "ip_addr": "127.0.0.1",
  "level": "error",
  "method": "POST",
  "msg": "/google-drive command crashed the com.mattermost-community.plugin-google-drive plugin. Please contact your system administrator",
  "path": "/api/v4/commands/execute",
  "request_id": "qpj6a49or7rj5q8jsjzwamj61w",
  "timestamp": "2024-12-04 18:38:42.609 +05:30",
  "user_id": "dp6nnhs3b7y8xmhqpx7kqchz4e"
}
```
Steps to reproduce:
1. Enable and setup the Google-drive plugin.
2. Enter the command either ""/google-drive notificaiton" or "/google-drive create" in the DM or any channel.
3. Check the error message received.

Screenshot:
![image](https://github.com/user-attachments/assets/9c7f30f0-005e-4cdc-9546-d8d37922861d)

**Comment by BenCookie95** [comment]
Fixed
